language: node_js
node_js:
  - "stable"
cache: yarn
install:
  - yarn install
script:
  - yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master